language: go

go:
 - 1.2

install:
 - wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.12.zip
 - unzip -q go_appengine_sdk_linux_amd64-1.9.12.zip
 - export PATH=$PATH:$PWD/go_appengine/

script:
 - goapp test

notifications:
  email:
    recipients:
      - imjasonh+travis@gmail.com
    on_success: never
    on_failure: change
